class BedrockProtocolInfo:
    LOGIN = 0x01
    PLAY_STATUS = 0x02
    SERVER_TO_CLIENT_HANDSHAKE = 0x03
    CLIENT_TO_SERVER_HANDSHAKE = 0x04
    DISCONNECT = 0x05
    RESOURCE_PACKS_INFO = 0x06
    RESOURCE_PACK_STACK = 0x07
    RESOURCE_PACK_CLIENT_RESPONSE = 0x08
    START_GAME = 0x09
    ADD_PLAYER = 0x0a
    ADD_ENTITY = 0x0b
    REMOVE_ENTITY = 0x0c
    MOVE_ENTITY = 0x0d
    MOVE_PLAYER = 0x0e
    CHAT = 0x0f
    SET_TIME = 0x10
    REQUEST_NETWORK_SETTINGS = 0x84
    NETWORK_SETTINGS = 0x85
    COMPRESSED_PACKET = 0xfe

    PLAY_STATUS_LOGIN_SUCCESS = 0x00
    PLAY_STATUS_FAILED_CLIENT = 0x01
    PLAY_STATUS_FAILED_SERVER = 0x02
    PLAY_STATUS_PLAYER_SPAWN = 0x03
